Include algorithm library. Allows Linux build.
resistiv/VibRipper pull request #2
Opened 2024-07-17 06:01 UTC by VoxelTek

The `std::replace` command would throw an error when compiling on Linux. By adding `#include <algorithm>`, this issue is fixed. With this change, the program now runs perfectly on Linux.

Linux build:
[VibRipper.zip](https://github.com/user-attachments/files/16260887/VibRipper.zip)

2024-07-17 15:51 UTC, resistiv requested changes
Howdy @VoxelTek! Thanks for the PR.

I don't believe the include you added is needed for ``VibRipper.cpp``, is it? I don't believe ``std::replace`` is used within that class, but I haven't touched this project in a bit. Let me know if you're able to remove that and if it still compiles fine!

If you're not able to remove it from ``VibRipper.cpp`` without the compiler whining, it might be best to only include it once in ``VibRipper.h``, so it's not spread across the class bodies.

Thank you again, keep me posted!!

2024-07-18 01:45 UTC, VoxelTek commented
Hey! My apologies, I added the library to all of them in a desperate attempt to get it to compile initially. Checking now, `VibRipper.cpp` does not need `<algorithm>`, and the tool compiles fine without it. I'll remove it from `VibRipper.cpp`, but I just wanted to clarify, should I also remove `#include <algorithm>` from `Unpacker` and `Repacker`, and instead place it in `VibRipper.h`?

2024-07-18 01:50 UTC, resistiv commented
No need to apologize!
Glad to get confirmation on ``VibRipper.cpp``! Thanks for checking.
As for the other two, I figure that having the include only in ``VibRipper.h`` would be cleaner, but since it's not necessary for ``VibRipper.cpp``, I think it'll be fine to leave the files as-is.

I'll go ahead and merge this in, thanks so much for your contribution!

2024-07-18 01:51 UTC, resistiv approved these changes

2024-07-18 01:51 UTC, merged

2024-07-18 01:53 UTC, VoxelTek commented
Glad I could lend a hand!